### ISSUE TITLE
A doubt in bias subspace calculation equation

### ISSUE THREAD

**Issue by tanmay17061** [pliang279/sent_debias#3]
Hi!
Thanks for the well laid-out explanation in your paper. I really enjoyed reading it.
I have a question from the paper, I hope that this is a correct place to ask it :-).

In equation (3) to calculate the bias subspace, I notice we are subtracting \mu_{j} from each template sentence embedding.
If I understand it correctly, it means removing the gender context (eg- the "male" context for sentences in \mathcal{R}\_{1} and the "female" context for sentences in \mathcal{R}\_{2}) from the sentences.
What is the motivation for this correction?

PS: In other papers like the one by (Bolukbasi et al., 2016), I notice they simply apply PCA over the difference of gender specific pairs (eg- \vec{he}-\vec{she}). This is easier for me to imagine as the vector difference simply gives us the direction of gender.

**Comment by Shamdan17** [comment]
@tanmay17061 Hello! I am having a similar question. Did you manage to find an intuitive way to think of it? Thanks!

**Comment by tanmay17061** [comment]
Hey @Shamdan17,
Yes, through the code I understood they are not calculating the gender subspace as described in the paper.
You can explore the code starting at [this](https://github.com/pliang279/sent_debias/blob/master/debias-BERT/experiments/run_classifier.py#L344) point. Finally from [this](https://github.com/pliang279/sent_debias/blob/1be02d4bc39585497ad292d7adbd5bc295d445fc/debias-BERT/experiments/run_classifier.py#L314) point I understand that they are simply doing:
```
for i = 1 to N:
    f_i = BERT encoded representation of female sentence (eg- "we assumed _she_ would explain the menu but nope!")
    m_i = similarly, male sentence (eg- "we assumed _he_ would explain the menu but nope!")
    mean_i = (f_i + m_i) / 2.0
    f_i := f_i - mean_i
    m_i := m_i - mean_i
apply PCA over the 2*N sentence representations hence generated to extract the gender components.
```

PS: this implementation is much more intuitive to me as (f_i - mean_i) represents the gender direction (likewise for m_i). I'm not sure why the equation in paper is not being used here.

**Comment by Shamdan17** [comment]
@tanmay17061 That makes sense, thank you very much!
